package snake.reverse

import snake.logic.{East, North, South, West}
import snake.{ChangeDir, ReverseGame, SnakeTestSuiteBase}

class ReverseTests extends SnakeTestSuiteBase {

    test("testReverseSimple") {
        checkGame(
            List(
                TestFrame(2,
                    """OO>..
                      |A....
                      |....."""),
                TestFrame(2,
                    """.OO>.
                      |A....
                      |....."""),
                TestFrame(2,
                    """..OO>
                      |A....
                      |....."""),
                TestFrame(2, List(ReverseGame(true)),
                    """.OO>.
                      |A....
                      |....."""),
                TestFrame(2,
                    """OO>..
                      |A....
                      |....."""),
            ), hint = "The game should reverse to earlier game states after enabling reverse mode."
        )
    }

    test("testReversePastStart") {
        checkGame(
            List(
                TestFrame(2,
                    """OO>..
                      |A...."""),
                TestFrame(2,
                    """.OO>.
                      |A...."""),
                TestFrame(2,
                    """..OO>
                      |A...."""),
                TestFrame(2,
                    """>..OO
                      |A...."""),
                TestFrame(2, List(ReverseGame(true)),
                    """..OO>
                      |A...."""),
                TestFrame(2,
                    """.OO>.
                      |A...."""),
                TestFrame(2,
                    """OO>..
                      |A....""")
            ), hint = "Reversing past the start of the game should keep the game at the initial position"
        )
    }

    test("testReverseGameOver") {
        checkGame(
            List(
                TestFrame(2,
                    """OO>..
                      |A...."""),
                TestFrame(2,
                    """.OO>.
                      |A...."""),
                TestFrame(2,
                    """..OO>
                      |A...."""),
                TestFrame(2, List(ChangeDir(North())),
                    """...OO
                      |A...^"""),
                TestFrame(2,
                    GameOverDisplay()),
                TestFrame(2,
                    GameOverDisplay()),
                TestFrame(2,
                    GameOverDisplay()),
                TestFrame(2, List(ReverseGame(true)),
                    """...OO
                      |A...^"""),
                TestFrame(2,
                    """..OO>
                      |A...."""),
                TestFrame(2,
                    """.OO>.
                      |A...."""),
                TestFrame(2,
                    """OO>..
                      |A...."""),
            ), hint = "Reversing from a game over state should immediately give the last non game over state"
        )
    }

    test("testChangeThePast") {
        checkGame(
            List(
                TestFrame(2,
                    """OO>..
                      |A....
                      |....."""),
                TestFrame(2,
                    """.OO>.
                      |A....
                      |....."""),
                TestFrame(2,
                    """..OO>
                      |A....
                      |....."""),
                TestFrame(2,
                    """>..OO
                      |A....
                      |....."""),
                TestFrame(2, List(ReverseGame(true)),
                    """..OO>
                      |A....
                      |....."""),
                TestFrame(2,
                    """.OO>.
                      |A....
                      |....."""),
                TestFrame(2,
                    """OO>..
                      |A....
                      |....."""),
                TestFrame(2, List(ReverseGame(false), ChangeDir(South())),
                    """.OO..
                      |A.v..
                      |....."""),
                TestFrame(2, List(ChangeDir(West())),
                    """..O..
                      |A<O..
                      |....."""),
                TestFrame(4,
                    """....A
                      |<OO..
                      |.....""")

        ), hint = "After reversing, it should be possible to keep playing, doing different actions than the previous time"
        )
    }

    test("testReverseLong") {
        checkGame(
            List(
                TestFrame(2,
                    """OO>..
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(2,
                    """.OO>.
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(2, List(ChangeDir(South()), ChangeDir(West())),
                    """..OO.
                      |A..v.
                      |.....
                      |.....
                      |....."""),
                TestFrame(2, List(ChangeDir(West())),
                    """...O.
                      |A.<O.
                      |.....
                      |.....
                      |....."""),
                TestFrame(2,
                    """.....
                      |A<OO.
                      |.....
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |<OO..
                      |.....
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |OOO.<
                      |.....
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |OOO<O
                      |.....
                      |.....
                      |....."""),
                TestFrame(4, List(ChangeDir(North())),
                    """...^A
                      |OOOOO
                      |.....
                      |.....
                      |....."""),
                TestFrame(2, List(ChangeDir(East())),
                    """..AO>
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(2,
                    """>.AOO
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(2,
                    """O>AOO
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(4,
                    """OO>OO
                      |OO.OO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(4,
                    GameOverDisplay()),
                TestFrame(4,
                    GameOverDisplay()),
                TestFrame(4, List(ReverseGame(true)),
                    """OO>OO
                      |OO.OO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(4,
                    """O>AOO
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(4, List(ReverseGame(false)),
                    """OO>OO
                      |OO.OO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(4, List(ChangeDir(South())),
                    """OOOOO
                      |OOvOO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |..vA.
                      |.....
                      |....."""),
                TestFrame(2, List(ChangeDir(East())),
                    """OOOOO
                      |OOOOO
                      |..O>A
                      |.....
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |..OO>
                      |..A..
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |>.OOO
                      |..A..
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |O>OOO
                      |..A..
                      |....."""),
                TestFrame(4, List(ChangeDir(South()), ChangeDir(East())),
                    GameOverDisplay()),
                TestFrame(4,
                    GameOverDisplay()),
                TestFrame(4, List(ReverseGame(true)),
                    """OOOOO
                      |OOOOO
                      |O>OOO
                      |..A..
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |>.OOO
                      |..A..
                      |....."""),
                TestFrame(4, List(ReverseGame(false)),
                    """OOOOO
                      |OOOOO
                      |O>OOO
                      |..A..
                      |....."""),
                TestFrame(4, List(ChangeDir(South())),
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.vA..
                      |....."""),
                TestFrame(2, List(ChangeDir(East())),
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.O>.A
                      |....."""),
                TestFrame(2,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.OO>A
                      |....."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.OOO>
                      |...A."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |>OOOO
                      |...A."""),
                TestFrame(4, List(ChangeDir(South())),
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |v..A."""),
                TestFrame(4, List(ChangeDir(East())),
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |O>.A."""),
                TestFrame(4,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OO>A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OOO>A"""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOO>"""),
                TestFrame(0,
                    GameOverDisplay()),
                TestFrame(0,
                    GameOverDisplay()),
                TestFrame(0,
                    GameOverDisplay()),
                TestFrame(0, List(ReverseGame(true)),
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOO>"""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OOO>A"""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |OO>A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |O>.A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |OOOOO
                      |v..A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |>OOOO
                      |...A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.OOO>
                      |...A."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.OO>A
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.O>.A
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |OOOOO
                      |.vA..
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |O>OOO
                      |..A..
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |>.OOO
                      |..A..
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |..OO>
                      |..A..
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |..O>A
                      |.....
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOOOO
                      |..vA.
                      |.....
                      |....."""),
                TestFrame(0,
                    """OOOOO
                      |OOvOO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(0,
                    """OO>OO
                      |OO.OO
                      |...A.
                      |.....
                      |....."""),
                TestFrame(0,
                    """O>AOO
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """>.AOO
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """..AO>
                      |OO.OO
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """...^A
                      |OOOOO
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """....A
                      |OOO<O
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """....A
                      |OOO.<
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """....A
                      |<OO..
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """.....
                      |A<OO.
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """...O.
                      |A.<O.
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """..OO.
                      |A..v.
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """.OO>.
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """OO>..
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """OO>..
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(0, List(ReverseGame(false)),
                    """.OO>.
                      |A....
                      |.....
                      |.....
                      |....."""),
                TestFrame(0, List(ChangeDir(South())),
                    """..OO.
                      |A..v.
                      |.....
                      |.....
                      |....."""),
                TestFrame(0, List(ChangeDir(West())),
                    """...O.
                      |A.<O.
                      |.....
                      |.....
                      |....."""),
                TestFrame(0,
                    """.....
                      |A<OO.
                      |.....
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |<OO..
                      |.....
                      |.....
                      |....."""),
                TestFrame(4, List(ChangeDir(South())),
                    """....A
                      |OOO..
                      |v....
                      |.....
                      |....."""),
                TestFrame(4, List(ChangeDir(East())),
                    """....A
                      |OOO..
                      |O>...
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |OOO..
                      |OO>..
                      |.....
                      |....."""),
                TestFrame(4,
                    """....A
                      |OO...
                      |OOO>.
                      |.....
                      |....."""),
            )
        )
    }
}
